version: "3.8"
services:
  postgresdb:
    container_name: quotes-database
    build:
      context: ./database
    volumes:
      - postgresdbdata:/data/db
    env_file:
      - ./env/postgres.env
  backend:
    container_name: quotes-backend
    build:
      context: ./backend
     #docerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
    env_file:
      - ./env/backend.env
    depends_on:
      - postgresdb
  frontend:
    container_name: quotes-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgresdbdata:
